# People {-}

**Leadership**

[Kay Jowers](https://nicholasinstitute.duke.edu/people/kay-jowers) - Director of the Just Environments Program in the Nicholas Institute for Energy, Environment & Sustainability 

[Elizabeth Albright](https://nicholas.duke.edu/people/faculty/albright) - Associate Professor of the Practice of Environmental Ethics and Sustainable Environmental Management

**Affiliated Faculty**

[Chris Timmins](https://business.wisc.edu/directory/profile/christopher-timmins/) - Professor of Economics

**Current Graduate RA's**

Jaeyong (Danny) Han

Liz Lu 

Sarah Raviola

Yu Ma


**Current Undergrad RA's**

Thomas Barker

Wendy Shi

Zhaoya Wu

Zoe Macomber

## Alums {-}

[Annabel (Qihui) Hu](https://www.heinz.cmu.edu/faculty-research/profiles/hu-qihui/), 2021 - PhD Candidate @ CMU Heinz

[Bryan Montes](https://www.linkedin.com/in/bryan-montes/), 2021 - Energy, Sustainability, and Infrastructure Consultant at Guidehouse

Cassandra Turk, 2021 

[Julia Marshall](), 2021 - 

[Nehal Jain](), 2021 - 

[Ryan Hastings](https://mobile.twitter.com/ryanjhast), 2021 - Econ PreDoc @ Wharton Real Estate

[Daisy (Xiaoou) Zhan](https://business.wisc.edu/directory/profile/xiaoou-zhan/), 2020 - PhD Candidate @ U Wisconsin School of Business

[Davis Berlind](https://davis-berlind.github.io/), 2020 - PhD Candidate @ UCLA Statistics

[Brian Wong](https://www.ornl.gov/staff-profile/brian-wong), 2019 - MBA Candidate @ Duke Fuqua

[Evelyn Garcia](), 2019 - 

[Jules Carter](), 2019 - 

[Spencer Yu](), 2019 - 

[Xueting Pi](https://www.arec.umd.edu/people/graduate-students), 2019 - PhD Candidate @ U of Maryland, Environmental Economics

[Anne Driscoll](http://www.adriscoll.com/), 2018 - Staff RA @ EJ Lab

[Ryan Hoecker](https://socialfinance.org/team/ryan-hoecker/), 2018 - Senior Associate @ Social Finance
