# Onboarding {-}

## Lab structure {-}

The lab consists of one Principal Investigator (PI), Kay Jowers (the Director of the Just Environments program at the Nicholas Institute and Kenan Institute), one staff as EJ Lab manager, faculty research partners, and graduate and undergraduate paid student research assistants. 

The research lab consisting of students, Dr. Jowers, and lab manager meet weekly in person.  Meetings start with a rose/bud/thorn check-in, followed by a presentation by a lab member, and a factoid or figure share by a third lab member. 

Mostly, each student is working on one project in collaboration with the PI or other faculty partner on a relatively long term basis. Research meetings between the lab PIs and students help define the structure and goals of the project, help to move research forward and troubleshoot things that come up throughout the process, but most work happens pretty independently. 

## How to Onboard to EJ Lab{-}
The following are instructions for how to begin a project with EJLab. To access our data on protected space on the virtual computer/remote desktop, you must have the following installed appropriately on your computer.  Accessing protected data from the Duke virtual computer rather than your personal laptop is of the utmost importance to be in compliance with data protection policies.

### Tasks for research affiliates and students
* **Duo/Multi-Factor Authentication (MFA):**  See the following two links from OIT for more information: https://oit.duke.edu/service/duo/ and registering a device with Duo: https://idms-mfa.oit.duke.edu/mfa/home

* **Install VPN**: To install VPN, follow these instructions from Duke: https://vcm.duke.edu/help/15 for Windows, Max, or Linux machines

* **Connect to VPN**: Instructions from Duke: https://oit.duke.edu/help/articles/kb0028460/  

Specifically, MFA is required when connecting to Duke's virtual private network (VPN). Open the Cisco AnyConnect application or visit https://portal.duke.edu.  Then, select the desired VPN (**vpn.duke.edu**) and click Connect.  Enter your NetID and password and click OK.  In the MFA Option field, select an option to receive a push notification to your mobile device, a phone call, or temporary passcodes.  Click Continue. You are connected to the VPN.

* **Download Remote Desktop Application**: See instructions for Windows, Max, or Linux here from Duke IT: https://vcm.duke.edu/help/15

* **Connect to EJ Lab virtual machine**: Open the Remote Desktop Application, click "+ Add" to add a new PC. The PC name is **see this link**.  Your netid and password are required to login.

* **OPTIONAL - Git account**: For users who will be coding, ensure you have a Git account and request access from EJLab staff.  Onboarding to GitHub is outlined in the GitHub-HelloWorld repo with video tutorial additionally located on EJ Lab network attached storage drive general/Projects/Onboarding


### Tasks for non-Duke-affiliated research affiliates:
* Guest affiliate account: Kay Jowers or lab manager should request a guest account from Duke OIT: https://accounts.oit.duke.edu/sponsor .  The affiliate will receive an email to confirm.

### Tasks specific to users with Duke-owned computers
* Users who have a Duke-owned computer may access EJLab network attached storage drives from their Duke-owned computer AND also by logging into the EJLab remote desktop.  Network attached storage drive links include the following and may or may not be availalbe to each user depending on the user's permissions:


### Tasks for EJ Lab staff for each new user:
* Research Toolkits:  Add the user's netid in Research Toolkits as part of team "Members" and as a separate indivudal team (e.g. Student_Sarah).  Once the user's netid is added to team "Members", the netid now has permissions to log into the EJ Lab remote computer. The user's netid as part of a separate team allows personalized permissions for each project folder.
* Create user folder in student or affiliate network attached storage drive
* If appropriate, invite user to Git account, invite users to specific GitHub repos as needed
* Set Permissions on network attached storage drives for each new netid
* request guest account, if applicable (see above)
* if any IT links are outdated above, email IT and request updated information




## Code Organization {-}

Code for lab projects all lives in the [**lab GitHub**](https://github.com/Duke-EJ-Lab). Many of the repos discussed below are set to only be accessible to members of the GitHub lab group, so be sure to request access. 




## Data Storage {-}

Data are stored on network attached storage drives accessible via the EJLab remote computer.

Remote computer is:[request specific name/path from EJ Lab staff, redacted for privacy]

Network attached storage drives are:

(1) For non-student partners: ejlab_partners
(2) For student and postdoctoral research: ejlab_students
(3) for project data: ejlab_general
(4) for project archive:ejlab_archive

Request specific pathways from EjLab staff. Redacted for privacy.


* **Data** 
1) `raw` is effectively a read-only folder. Data is added relatively rarely and it's important when things are added to the raw folder to document well **when** the data was downloaded, **how** to obtain the data (a link to download/an email for who to contact to get access), and **what** the data means (a data dictionary). More details about the exact way to do this are in the [workflow section](#databank).

2) `clean` holds processed data that you might want to directly pull into a project. For something to get added to clean a few conditions need to be met: the raw data is in the `raw` folder, and the code that cleans it is in the lab `cleaning` github. This is only for data that might be useful for someone else on a different lab project. A dataset to include might be: the average PM for every year 2000-2020 for each county in the contiguous US. A dataset not to include might be: a panel that includes 21 day rolling mean county level PM observation that you built to purpose for a model. 

* **Projects**

 `projects` is the folder that contains a folder for each active or completed project. While we'd recommend a structure that at least separates your `raw` data, `clean` data and any `docs` files you have (eg literature reviews, research updates, other notes to self, etc) - this is a space each RA can do whatever they please with. 


Below is a minimal representation of what the Box structure looks like. 

```
ejlab
 ├── projects
 │   ├── covid_housing_precarity
 │   ├── covid_rental_discrimination
 │   └── cafos_nc 
 ├── data
 │	 ├── raw
 |       ├── Durham County 
 |       ├── Durham County 
 │	 ├── clean
 |       ├── Durham County
 
```

### VM's {-}

There are a few datasets that should only exist on **Duke owned machines** (the VM's) or (if they have even higher protections) that can only exist in the **protected research data network** (PRDN). Information on getting access to those spaces can be found in the onboarding section. This includes the original datasets, and ANY data that is created from it/combined with it/modeled using it, excluding simple tables that might be need to go in a publication. The datasets currently used in lab that these protections apply to are: 

* InfoUSA

For projects that work with a protected dataset, all of the work will occur on the VM itself or Duke-owned laptops.

### Individual Code Organization {-}

Each lab project will have it's own GitHub repository, which should be reproducible by people within lab. All lab projects start from a [reproducible project template](https://github.com/Duke-EJ-Lab/reproducible_project_template). Starting all projects from this file structure gives a framework that helps make our data and code more uniform, helping with reproducibility and keeping institutional knowledge as students join and leave projects.

This template is set up with example R files, but the same ideas apply regardless of the language you're using. The template repo itself documents what should go in what folder, and includes examples of documentation and commenting throughout code files. An example of the template in use is the [COVID housing precarity](https://github.com/Duke-EJ-Lab/covid_housing_precarity) repo. External examples for how a publishable repo can look: [The Changing Risk and Burden of Wildfire in the United States](https://github.com/echolab-stanford/wildfire-map-public). 

Once you have access to the lab GitHub, you should be able to create repositories for each of your own projects. Details on that can be found in the [section on starting a project](#startup).

### Lab Code Organization {-}

There are two communal GitHub code repositories to know about: 

* The [lab.tools](https://github.com/Duke-EJ-Lab/lab.tools) repo, which is an R package that everyone can add to and use in their code. You can find more information about how to contribute in the workflow section. It contains some helpful little functions like `detach_all_packages()` that lets you quickly wipe all the loaded functions from your environment - as well as some helpful analysis functions like `merge_verbose()` which wraps the normal merge function but outputs some info on the success of the merge or `simplify_and_combine_shapefiles()` which takes in a vector of file paths, simplifies the shapefiles and returns a master file, which is useful when data is served at a state level. 
    * You can install the lab.tools package through first loading the `devtools` package, then running `install_github("Duke-EJ-Lab/lab.tools")`. Then just load as a normal library using `library(lab.tools)`.
* The [general_cleaning](https://github.com/Duke-EJ-Lab/general_cleaning) repo, which serves to ensure we know the origin of all our communal lab data. There's more information about how to interact with the repo in the workflow section. 

In addition to the code repositories, this [EJ_Lab_Starter_Guide](https://github.com/Duke-EJ-Lab/EJ_Lab_Starter_Guide) repo is something you can access and update. Details on how to do that are in the [guide](#guide) section. 

## Basics of GitHub {-}

The purpose is version control for coding.

GitHub uses "repositories" (repos) as buckets that contain individual projects. 

A **commit** is basically like saving your progress. You're telling git to pay attention and create a save point of what's changed since you last committed. This is the building block of a repo, each commit should be a bite sized change in your work.

A **push** is sending your commits to the cloud. Until you do this, your commits only exist on your computer, and if your colleagues look at your online GitHub repo nothing will have changed. 

A **pull** is telling Git to check if anyone else has changed the online repo, and updating what's on your computer to match. 

That's pretty much all you need to know to get started, and you'll see more about **commits** and **pushing** in the next section. In our usage, we'll always talk about commiting then immediately pushing afterwards, since not doing so can cause complications. From here on we're describing GitHub through the desktop app because that's the easiest way to learn about GitHub. 

